language: elixir
elixir:
  - 1.10.4
otp_release:
  - 22.0
sudo: false
env:
  global:
    - ELIXIR_ASSERT_TIMEOUT=2000
    - TINKOFF_TOKEN=123
    - TINKOFF_BROKER_ACCOUNT_ID=1234
before_script:
  - mix deps.get
script:
  - mix test